# Install required plugins
required_plugins = ["vagrant-hostsupdater"]
required_plugins.each do |plugin|
    exec "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip: "192.168.10.100"
    # app.hostsupdater.aliases = ["development.local"]
    # app.vm.synced_folder "html", "/var/www/html"
    app.vm.provision "ansible" do |ansible|
      ansible.playbook="main.yaml"
    end
  end

end